### ISSUE TITLE
Preserve Feature IDs

### ISSUE THREAD

**Issue by SamiPatanen** [mapbox/supercluster.hpp#18]
(Continued from https://github.com/mapbox/mapbox-gl-native/issues/12347)

Hi!

Is there any possibility to preserve feature IDs? Removing them leads to undocumented surprises downstream.

**Comment by mourner** [comment]
Yes, this will be addressed shortly by https://github.com/mapbox/supercluster.hpp/pull/16

**Comment by SamiPatanen** [comment]
While trying a workaround for this issue, I have discovered that feature properties also get erased (see gl-native issue). Does #16 also preserve properties?

**Comment by mourner** [comment]
@SamiPatanen they shouldn't; at least Supercluster doesn't (as you can see in the tests).

**Comment by SamiPatanen** [comment]
True, I tested without clustering and features are still removed. False alarm.
