### ISSUE TITLE
Cluster geometry collections

### ISSUE THREAD

**Issue by 1ec5** [mapbox/supercluster.hpp#5]
`Supercluster`’s constructor requires a `GeoJSONFeatures` (aka feature collection). However, it should be possible to cluster geometry collections as well.

One complication is that `getTile()` currently synthesizes a feature with `cluster` and `point_count` properties for each cluster, whereas a geometry collection contains only geometries.

/ref mapbox/mapbox-gl-native#7622
/cc @mourner @jfirebaugh

**Comment by mourner** [comment]
I don't think we should support this — it's a weird use case that will makes the code and documentation more confusing.

**Comment by mourner** [comment]
Closing for now.
